//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denomica.JsonLD.Extensions.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Denomica.JsonLD.Extensions.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html class=&quot;js template-product sticky-header-initialized sticky-header-fixed sticky-header-show&quot; lang=&quot;fi&quot; style=&quot;--sticky-header-margin-top: 138px;&quot;&gt;
        ///&lt;iframe height=&quot;0&quot; width=&quot;0&quot; style=&quot;display: none; visibility: hidden;&quot;&gt;&lt;/iframe&gt;
        ///&lt;head&gt;
        ///    &lt;script type=&quot;text/javascript&quot; async=&quot;&quot; src=&quot;https://d33a6lvgbd0fej.cloudfront.net/script_tag/secomapp.scripttag.js?shop=kalevalakoru.myshopify.com&quot;&gt;&lt;/script&gt;
        ///    &lt;script type=&quot;text/javascript&quot; async=&quot;&quot; src=&quot;https://cdn-loyalty.yotpo.com/loade [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLPage001 {
            get {
                return ResourceManager.GetString("HTMLPage001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@context&quot;: &quot;https://schema.org&quot;,
        ///  &quot;@graph&quot;: [
        ///    {
        ///      &quot;@context&quot;: &quot;https://schema.org&quot;,
        ///      &quot;@type&quot;: &quot;Organization&quot;,
        ///      &quot;url&quot;: &quot;https://www.verkkokauppa.com/&quot;,
        ///      &quot;name&quot;: &quot;Verkkokauppa.com&quot;,
        ///      &quot;legalName&quot;: &quot;Verkkokauppa.com Oyj&quot;,
        ///      &quot;vatID&quot;: &quot;1456344-5&quot;,
        ///      &quot;address&quot;: {
        ///        &quot;@type&quot;: &quot;PostalAddress&quot;,
        ///        &quot;streetAddress&quot;: &quot;Tyynenmerenkatu 11&quot;,
        ///        &quot;addressLocality&quot;: &quot;Helsinki&quot;,
        ///        &quot;addressCountry&quot;: &quot;FI&quot;,
        ///        &quot;addressRegion&quot;: &quot;Uusimaa&quot;,
        ///        &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSONLD001 {
            get {
                return ResourceManager.GetString("JSONLD001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@context&quot;: &quot;https://schema.org&quot;,
        ///  &quot;@graph&quot;: [
        ///    {
        ///      &quot;@context&quot;: &quot;http://schema.org&quot;,
        ///      &quot;@type&quot;: &quot;Product&quot;,
        ///      &quot;name&quot;: &quot;Amuletti-riipus Aurinkoleijona pronssi&quot;,
        ///      &quot;image&quot;: &quot;https://www.kalevala.fi/cdn/shop/products/Amulettiriipusaurinkoleijonapronssi327031360-542949_large.jpg%3Fv=1709845250&quot;,
        ///      &quot;aggregateRating&quot;: {
        ///        &quot;@context&quot;: &quot;https://schema.org&quot;,
        ///        &quot;@type&quot;: &quot;AggregateRating&quot;,
        ///        &quot;ratingValue&quot;: 4.8,
        ///        &quot;reviewCount&quot;: 40
        ///      },
        ///      &quot;offers&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSONLD002 {
            get {
                return ResourceManager.GetString("JSONLD002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@context&quot;: &quot;https://schema.org&quot;,
        ///  &quot;@graph&quot;: [
        ///    {
        ///      &quot;@context&quot;: &quot;https://schema.org&quot;,
        ///      &quot;@type&quot;: &quot;Product&quot;,
        ///      &quot;name&quot;: &quot;TP-LINK Deco X50-5G Dual Band 5G/4G/3G -modeemi ja WiFi6 -tukiasema&quot;,
        ///      &quot;image&quot;: [
        ///        &quot;https://cdn.verk.net/kuvastin/w:576/h:576/rt:fit/q:80/sh:0.5/plain/images/31/2_865561-501x836.jpeg&quot;,
        ///        &quot;https://cdn.verk.net/kuvastin/w:576/h:576/rt:fit/q:80/sh:0.5/plain/images/80/2_865561-497x793.jpeg&quot;,
        ///        &quot;https://cdn.verk.net/kuvastin/w:576/h:576/rt:fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSONLD003 {
            get {
                return ResourceManager.GetString("JSONLD003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;@context&quot;: &quot;https://schema.org&quot;,
        ///    &quot;@type&quot;: &quot;ProductGroup&quot;,
        ///    &quot;productGroupID&quot;: &quot;234&quot;,
        ///    &quot;name&quot;: &quot;US ALICE taisteluvyö, ylijäämä - Varusteleka.com&quot;,
        ///    &quot;description&quot;: &quot;Käytettyjä jenkkiarmeijan ALICE-tetsarivöitä. Aitoon ALICE-tavaraan voi luottaa - hyvä käyttää ja kestää varmasti. Katso saatavuus ja hanki omasi!&quot;,
        ///    &quot;sku&quot;: &quot;234&quot;,
        ///    &quot;gtin&quot;: &quot;x&quot;,
        ///    &quot;mpn&quot;: &quot;us-alicepbk&quot;,
        ///    &quot;url&quot;: &quot;https://www.varusteleka.com/fi/product/us-alice-taisteluvyo-ylijaama/234&quot;,
        ///    &quot;brand&quot;: {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSONLD004 {
            get {
                return ResourceManager.GetString("JSONLD004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;@context&quot;: &quot;https://schema.org&quot;,
        ///    &quot;@type&quot;: &quot;ProductGroup&quot;,
        ///    &quot;productGroupID&quot;: &quot;989&quot;,
        ///    &quot;name&quot;: &quot;BW talvihattu, Flecktarn, ylijäämä - Varusteleka.com&quot;,
        ///    &quot;description&quot;: &quot;Bundeswehrin talvihattua pitää joko siksi, että se on tosi hyvä talvipäähine, tai siksi, että se on niin älyttömän ruma. Toimii erinomaisesti kypärän alla. Hank&quot;,
        ///    &quot;sku&quot;: &quot;989&quot;,
        ///    &quot;gtin&quot;: &quot;91210121&quot;,
        ///    &quot;mpn&quot;: &quot;bw-fldmtzewi&quot;,
        ///    &quot;url&quot;: &quot;https://www.varusteleka.com/fi/product/bw-talvihattu-flecktarn-ylijaama/989&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSONLD005 {
            get {
                return ResourceManager.GetString("JSONLD005", resourceCulture);
            }
        }
    }
}
